# Generated by Django 5.2.1 on 2025-06-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_remove_boleta_usuario_boleta_usuario_id_unico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='total',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleboleta',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
